---
- name: "Debian | check sublime build"
  command: "/usr/bin/subl --version"
  register: __build

- include: debian_install.yml
  when: "{{ __build.stdout | regex_replace('[^\\d]+', '') | int }} != sublime_build"
