---
- name: "Debian | ensure user directory is present"
  file:
    dest: "{{ ansible_user_dir }}/.config/sublime-text-3/Packages/User"
    state: directory

- name: "Debian | configure sublime user settings"
  template:
    src: ../templates/Preferences.sublime-settings.j2
    dest: "{{ ansible_user_dir }}/.config/sublime-text-3/Packages/User/Preferences.sublime-settings"
