---
- name: "OS X | check sublime build"
  shell: "/Applications/Sublime\ Text.app/Contents/MacOS/Sublime\ Text --version | awk '{print $4}'"
  register: __build

- include: osx_install.yml
  when: __build != sublime_build
