---
- name: "OS X | check sublime build"
  command: "/Applications/Sublime\\ Text.app/Contents/MacOS/Sublime\\ Text --version"
  register: __build

- include: osx_install.yml
  when: "{{ __build.stdout | regex_replace('[^\\d]+', '') | int }} != sublime_build"
