---
- name: "OS X | download sublimetext.dmg"
  get_url:
    url: "{{ __url_dmg }}"
    dest: "{{ __tmp_dmg }}"

- name: "OS X | mount sublimetext.dmg"
  command: "hdiutil attach {{ __tmp_dmg }}"
  args:
    chdir: /tmp

- name: "OS X | ensure sublimetext is present"
  copy:
    src: "{{ __mount }}/Sublime Text.app"
    dest: "/Applications"
    mode: "u=rwx,g=rx,o=rx"

- name: "OS X | unmount sublimetext.dmg"
  command: "hdiutil detach {{ __mount | regex_replace(' ', '\\ ') }}"
